/**
 * Popup script for YDL GUI Helper.
 * Handles: i18n hydration, supported-site detection, deep link dispatch,
 * and a fallback hint when the desktop app likely isn't installed.
 */

const SUPPORTED_SITES = [
  { name: "YouTube",    domains: ["youtube.com", "youtu.be"] },
  { name: "Bilibili",   domains: ["bilibili.com", "b23.tv"] },
  { name: "Twitch",     domains: ["twitch.tv"] },
  { name: "Vimeo",      domains: ["vimeo.com"] },
  { name: "Dailymotion",domains: ["dailymotion.com"] },
  { name: "Niconico",   domains: ["nicovideo.jp"] },
  { name: "Twitter / X",domains: ["twitter.com", "x.com"] },
  { name: "Instagram",  domains: ["instagram.com"] },
  { name: "TikTok",     domains: ["tiktok.com"] },
  { name: "Facebook",   domains: ["facebook.com", "fb.watch"] },
  { name: "Reddit",     domains: ["reddit.com"] },
  { name: "SoundCloud", domains: ["soundcloud.com"] },
  { name: "Bandcamp",   domains: ["bandcamp.com"] },
  { name: "Crunchyroll",domains: ["crunchyroll.com"] },
];

const ALL_DOMAINS = SUPPORTED_SITES.flatMap((s) => s.domains);

const t = (key) => chrome.i18n.getMessage(key) || key;

function isSupportedUrl(url) {
  if (!url) return false;
  try {
    const host = new URL(url).hostname;
    return ALL_DOMAINS.some((d) => host === d || host.endsWith("." + d));
  } catch {
    return false;
  }
}

function toNetscapeLine(c) {
  const domain = c.domain.startsWith(".") ? c.domain : "." + c.domain;
  const flag = c.domain.startsWith(".") ? "TRUE" : "FALSE";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
  return `${domain}\t${flag}\t${c.path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`;
}

async function getCookieText(url) {
  const cookies = await chrome.cookies.getAll({ url });
  if (!cookies?.length) return "";
  const header = "# Netscape HTTP Cookie File\n# Generated by YDL GUI Browser Extension\n\n";
  return header + cookies.map(toNetscapeLine).join("\n");
}

function buildDeepLink(videoUrl, cookieText) {
  const params = new URLSearchParams();
  params.set("url", videoUrl);
  if (cookieText) {
    params.set("cookies", btoa(encodeURIComponent(cookieText)));
  }
  return `ytdlp-gui://download?${params.toString()}`;
}

/** Hydrate every [data-i18n] node with its localized message. */
function applyI18n() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    const msg = t(key);
    if (msg) el.textContent = msg;
  });
}

function renderSupportedSites() {
  const container = document.getElementById("sites");
  container.replaceChildren(
    ...SUPPORTED_SITES.map((s) => {
      const span = document.createElement("span");
      span.className = "site-chip";
      span.textContent = s.name;
      return span;
    })
  );
}

function setStatus(kind, key) {
  const el = document.getElementById("status");
  const text = document.getElementById("status-text");
  el.classList.remove("pill-ok", "pill-bad", "pill-muted");
  el.classList.add(
    kind === "ok" ? "pill-ok" : kind === "bad" ? "pill-bad" : "pill-muted"
  );
  text.textContent = t(key);
}

document.addEventListener("DOMContentLoaded", async () => {
  applyI18n();
  renderSupportedSites();

  const sendBtn = document.getElementById("send-btn");
  const btnText = document.getElementById("btn-text");
  const urlPreview = document.getElementById("url-preview");
  const sendCookies = document.getElementById("send-cookies");
  const cookieRow = document.getElementById("cookie-row");
  const fallback = document.getElementById("fallback");

  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  const pageUrl = tab?.url || "";

  if (!isSupportedUrl(pageUrl)) {
    setStatus("bad", "popupUnsupported");
    sendBtn.disabled = true;
    sendCookies.disabled = true;
    cookieRow.style.opacity = "0.55";
    return;
  }

  setStatus("ok", "popupSupported");
  urlPreview.hidden = false;
  urlPreview.textContent = pageUrl;
  sendBtn.disabled = false;

  sendBtn.addEventListener("click", async () => {
    sendBtn.disabled = true;
    btnText.textContent = t("popupSending");
    fallback.hidden = true;

    try {
      const cookieText = sendCookies.checked ? await getCookieText(pageUrl) : "";
      const deepLink = buildDeepLink(pageUrl, cookieText);

      // Navigating the popup itself triggers the OS protocol handler. The popup
      // closes when the OS handler takes over. If the popup is still here a
      // moment later, the handler probably didn't fire — show the install hint.
      window.location.href = deepLink;

      btnText.textContent = t("popupSent");
      setTimeout(() => {
        // Still alive? Likely no app handler registered.
        fallback.hidden = false;
        sendBtn.disabled = false;
        btnText.textContent = t("popupSendBtn");
      }, 1500);
    } catch {
      btnText.textContent = t("popupFailed");
      sendBtn.disabled = false;
    }
  });
});
